/** Payload generated by the official Agentcard browser SDK. Never log captured requests. */
export type CardCheckoutInput = {
  agentId: string; merchant: string; checkoutOrigin: string; amountMinor: number; currency: 'usd'
  authorization: Record<string, unknown> & { psp: string; mode: string; request: { url: string; method: string; headers: Record<string, string>; body: string } }
}
export type CardCheckoutStatus = 'pending_approval' | 'queued' | 'submitting' | 'awaiting_provider' | 'unknown' | 'confirmed' | 'failed' | 'rejected' | 'expired'
export type CardPurchaseCart = { hash: string; merchant: string; merchant_name: string; totalCents: number; approvedCeilingCents?: number | null; items: Array<{ name: string; qty: number; priceCents?: number; product_id?: string | null }> }
export type CardDeliveryAddress = { street: string; city: string; state: string; zip: string; address2?: string; phone?: string; name?: string; country?: string; can_leave_at_door?: boolean }
export type CardPurchaseTurn = { id: string; agentId: string; status: 'running' | 'complete' | 'unknown'; reply: string | null; carts: CardPurchaseCart[]; error: string | null }
export type CardCheckout = {
  id: string; agentId: string; provider: string; rail: 'browser' | 'purchase'; processorIntentId: string; merchant: string; checkoutOrigin: string; amountMinor: number; currency: 'usd'
  status: CardCheckoutStatus; operationHash: string; usdReservedMicros: string; usdSettledMicros: string | null
  createdAt: string; expiresAt: string; approvalUrl: string; error: string | null
  cart?: CardPurchaseCart
  deliveryAddress?: CardDeliveryAddress
  orderId?: string
  /** Owner-only provider approval link. Never log it. */
  providerApprovalUrl?: string
  /** Payment settlement does not imply merchant fulfillment. */
  merchantOrderConfirmed: boolean
}
export type CardCheckoutPermission = { grantId: string; enabled: boolean; revision: number }
/** Private SDK protocol response; never put in an agent prompt, receipt or log. */
export type CardCheckoutReplay = Record<string, unknown>
