AGENTIS_API_URL={{AGENTIS_API_URL}}
AGENTIS_FACILITATOR_ID={{FACILITATOR_ID}}
AGENTIS_HEARTBEAT_SECRET={{HEARTBEAT_SECRET}}
AGENTIS_PUBLIC_URL=

NETWORK={{NETWORK}}
ACCEPTED_MINT={{ACCEPTED_MINT}}
FACILITATOR_FEE_BPS={{FEE_BPS}}
FACILITATOR_PORT=3000
DATABASE_PATH=data/facilitator.db

KORA_RPC_URL=http://localhost:8080/
KORA_API_KEY={{KORA_API_KEY}}
KORA_PORT=8080
SOLANA_RPC_URL=https://api.devnet.solana.com
KORA_PRIVATE_KEY=

ADMIN_TOKEN=change-me
DEFAULT_SELLER_PAY_TO=
DEFAULT_SELLER_BALANCE_USD=0
